# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - cmake . && make
addons:
  apt:
    packages:
    - cmake
    - freeglut3
    - freeglut3-dev
    - libxmu-dev
    - libxi-dev
    - libglpk-dev
    - liblog4cxx-dev

